apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: kafka-service
  ports:
    - targetPort: 9092
      port: 9092